language: python

jobs:
  include:
    - python: 3.7
    - python: 3.8

before_install:
  - python --version
  - uname -a

install:
   - pip install -U git+https://github.com/sonntagsgesicht/auxilium
   - auxilium setup

script:
   - auxilium simple
